CREATE TABLE CLIENTE(
	TIPO VARCHAR(1) NOT NULL,
	CPF_CNPJ VARCHAR(14) NOT NULL,
	RAZAO_SOCIAL VARCHAR(60) NOT NULL,
	NOME_FANTASIA VARCHAR(30) NOT NULL, 
	ENDERECO VARCHAR(70)	
);
ALTER TABLE ADD CONSTRAINT CLIENTE_PK PRIMARY KEY (CPF_CNPJ,TIPO);

CREATE TABLE UNIDADE_MEDIDA(
	CODIGO VARCHAR(2) NOT NULL,
	DESCRICAO VARCHAR(20) NOT NULL
);
ALTER TABLE UNIDADE_MEDIDA ADD CONSTRAINT UNIDADE_MEDIDA_PK PRIMARY KEY (CODIGO);

CREATE TABLE PRODUTO(
	CODIGO VARCHAR(6) NOT NULL, 
	DESCRICAO VARCHAR(50) NOT NULL, 
	TIPO VARCHAR(1) NOT NULL,	
	UNIDADE_MEDIDA VARCHAR(2) NOT NULL,
	QUANTIDADE NUMERIC(8,3) NOT NULL,
	VALOR NUMERIC(14,2) NOT NULL,
);
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_PK PRIMARY KEY (CODIGO);
ALTER TABLE PRODUTO ADD CONSTRAINT PRODUTO_FK FOREIGN KEY (UNIDADE_MEDIDA) REFERENCES UNIDADE_MEDIDA(CODIGO);

CREATE TABLE VENDA_CABECALHO(
	CODIGO VARCHAR(6) NOT NULL,
	SERIE VARCHAR(3) NOT NULL,
	DT_EMISSAO DATE NOT NULL,
	CLIENTE VARCHAR(30) NOT NULL,
	TIPO VARCHAR(1) NOT NULL,
	VALOR_VENDA NUMERIC(14,2)
);
ALTER TABLE VENDA_CABECALHO ADD CONSTRAINT VENDA_CABECALHO_PK PRIMARY KEY (CODIGO,SERIE);
ALTER TABLE VENDA_CABECALHO ADD CONSTRAINT VENDA_CABECALHO_FK FOREIGN KEY(CLIENTE,TIPO) REFERENCES PRODUTO(CPF_CNPJ,TIPO);
 
CREATE TABLE VENDA_ITEM(
	CODIGO_VENDA VARCHAR(6) NOT NULL,
	SERIE_VENDA VARCHAR(3) NOT NULL,
	ITEM NUMERIC(3) NOT NULL,
	PRODUTO VARCHAR(6) NOT NULL,
	QUANTIDADE NUMERIC(8,3),
	VALOR_PRODUTO NUMERIC(14,2),
	VALOR_ITEM NUMERIC(14,2),
);
ALTER TABLE VENDA_ITEM ADD CONSTRAINT VENDA_ITEM_PK PRIMARY KEY (CODIGO_VENDA, SERIE_VENDA, ITEM);
ALTER TABLE VENDA_ITEM ADD CONSTRAINT VENDA_ITEM_FK FOREIGN KEY (CODIGO_VENDA, SERIE_VENDA) REFERENCES VENDA_CABECALHO(CODIGO_VENDA,SERIE_VENDA);